apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-api-config
  namespace: titanic-api
data:
  DATABASE_HOST: postgres-service
  DATABASE_PORT: "5432"
  DATABASE_NAME: titanic
  FLASK_ENV: development
  LOG_LEVEL: INFO
