apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-api-config
  namespace: titanic-api
  labels:
    app: titanic-api
data:
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "titanic"
  # Add any non-sensitive configuration here