apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secret.yaml
  - 03-postgres-pvc.yaml
  - 04-postgres.yaml
  - 05-deployment.yaml
  - 06-service.yaml
  - 07-hpa.yaml
  - 08-pdb.yaml
  - 09-network-policy.yaml
  - 10-resourcequota.yaml

labels:
  - pairs:
      app: titanic-api
      managed-by: kustomize