apiVersion: v1
kind: Namespace
metadata:
  name: titanic-api-dev
  labels:
    name: titanic-api
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: titanic-api-staging
  labels:
    name: titanic-api
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: titanic-api-prod
  labels:
    name: titanic-api
    environment: production