apiVersion: v1
kind: Secret
metadata:
  name: titanic-api-secret
  namespace: titanic-api
  labels:
    app: titanic-api
type: Opaque
stringData:
  DATABASE_USER: "titanic_user"
  DATABASE_PASSWORD: m415sYueQhrMk8Bv_ikvUQ
  SECRET_KEY: 8de2243734dfc8efc0f2feb0aea93d6d6b1019213fe81261be93be571d49ffc7
  # Base64 encoding will be done automatically