apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: titanic-api-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: titanic-api
    count: 3

images:
  - name: titanic-api
    newName: ghcr.io/isshy35/titanic-api
    newTag: staging-latest

configMapGenerator:
  - name: titanic-api-config
    behavior: merge
    literals:
      - FLASK_ENV=staging
      - LOG_LEVEL=INFO